name: KDM-ML
channels:
  - intel
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn
  - hdbscan
  - pandas
  - numpy
  - matplotlib=3.3
  - jupyter
  - seaborn
  - pillow
  - graphviz
  - pygraphviz
  - pyamg
  - jupyterlab
  - scikit-learn-intelex
